language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin/1.3.12
  matrix:
   - SCRIPT=ffcall
   - SCRIPT=asdf
   - SCRIPT=ecl
   - SCRIPT=sbcl-build
   - SCRIPT=quicklisp 

os:
  - linux

cache:
  directories:
    - $HOME/.roswell

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then ros install snmsts/sn.github fukamachi/dexador roswell/sbcl_bin lake;lake-tools dump; fi
  - if [ x$ADD_CACHE != x ] ; then ros install $ADD_CACHE ;fi

script:
  - cd $SCRIPT;lake
